## REMEMBER TO SET UP YOUR GITHUB REPO FOR TRAVIS
## Go to: https://travis-ci.org/obophenotype for details
sudo: required

services:
  - docker

before_install:
  - docker pull obolibrary/odkfull

jdk:
  - oraclejdk11

#after_success:
#  coveralls

# whitelist
branches:
  only:
    - master
    - test-travis

### Add your own lists here
### See https://github.com/INCATools/ontology-development-kit/issues/35
# who gets notified if build-status changes
notifications:
  email:
    recipients:
      - dr.sebastian.koehler@gmail.com
      - peter.robinson@jax.org
      - Leigh.Carmody@jax.org
      - vasilevs@ohsu.edu
      - nicolas.matentzoglu@gmail.com
    on_success: change
    on_failure: always

# perform quality checks
script: 
  - cd src/ontology && sh hpo-qc-pipeline.sh
